<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Frontend asset protection
    |--------------------------------------------------------------------------
    |
    | When enabled, Blade uses obfuscated JS from public/assets/protected/js
    | (generated by: npm run build:protect). Run that before production deploy.
    |
    */

    'protection_enabled' => (bool) env('ASSET_PROTECTION', env('APP_ENV') === 'production'),

    /*
    |--------------------------------------------------------------------------
    | Client hardening (discourage view-source / DevTools on app pages)
    |--------------------------------------------------------------------------
    |
    | Blocks context menu and common shortcuts. This is bypassable — it only
    | deters casual copying, not determined users.
    */

    'client_hardening' => (bool) env('CLIENT_HARDENING', env('APP_ENV') === 'production'),

    /*
    |--------------------------------------------------------------------------
    | Block common scraper / downloader user-agents on panel routes
    |--------------------------------------------------------------------------
    */

    'block_scrapers' => (bool) env('BLOCK_SCRAPERS', true),

];
