<?php

/**
 * Dial codes for country selector (registration + admin user forms).
 *
 * @return list<array{name: string, code: string, flag: string}>
 */
return [
    'dial_codes' => [
        ['name' => 'Afghanistan', 'code' => '+93', 'flag' => '🇦🇫'],
        ['name' => 'Albania', 'code' => '+355', 'flag' => '🇦🇱'],
        ['name' => 'Algeria', 'code' => '+213', 'flag' => '🇩🇿'],
        ['name' => 'Argentina', 'code' => '+54', 'flag' => '🇦🇷'],
        ['name' => 'Australia', 'code' => '+61', 'flag' => '🇦🇺'],
        ['name' => 'Austria', 'code' => '+43', 'flag' => '🇦🇹'],
        ['name' => 'Bahrain', 'code' => '+973', 'flag' => '🇧🇭'],
        ['name' => 'Bangladesh', 'code' => '+880', 'flag' => '🇧🇩'],
        ['name' => 'Belgium', 'code' => '+32', 'flag' => '🇧🇪'],
        ['name' => 'Brazil', 'code' => '+55', 'flag' => '🇧🇷'],
        ['name' => 'Canada', 'code' => '+1', 'flag' => '🇨🇦'],
        ['name' => 'Chile', 'code' => '+56', 'flag' => '🇨🇱'],
        ['name' => 'China', 'code' => '+86', 'flag' => '🇨🇳'],
        ['name' => 'Colombia', 'code' => '+57', 'flag' => '🇨🇴'],
        ['name' => 'Czech Republic', 'code' => '+420', 'flag' => '🇨🇿'],
        ['name' => 'Denmark', 'code' => '+45', 'flag' => '🇩🇰'],
        ['name' => 'Egypt', 'code' => '+20', 'flag' => '🇪🇬'],
        ['name' => 'Finland', 'code' => '+358', 'flag' => '🇫🇮'],
        ['name' => 'France', 'code' => '+33', 'flag' => '🇫🇷'],
        ['name' => 'Germany', 'code' => '+49', 'flag' => '🇩🇪'],
        ['name' => 'Greece', 'code' => '+30', 'flag' => '🇬🇷'],
        ['name' => 'Hong Kong', 'code' => '+852', 'flag' => '🇭🇰'],
        ['name' => 'Hungary', 'code' => '+36', 'flag' => '🇭🇺'],
        ['name' => 'India', 'code' => '+91', 'flag' => '🇮🇳'],
        ['name' => 'Indonesia', 'code' => '+62', 'flag' => '🇮🇩'],
        ['name' => 'Iran', 'code' => '+98', 'flag' => '🇮🇷'],
        ['name' => 'Iraq', 'code' => '+964', 'flag' => '🇮🇶'],
        ['name' => 'Ireland', 'code' => '+353', 'flag' => '🇮🇪'],
        ['name' => 'Israel', 'code' => '+972', 'flag' => '🇮🇱'],
        ['name' => 'Italy', 'code' => '+39', 'flag' => '🇮🇹'],
        ['name' => 'Japan', 'code' => '+81', 'flag' => '🇯🇵'],
        ['name' => 'Jordan', 'code' => '+962', 'flag' => '🇯🇴'],
        ['name' => 'Kenya', 'code' => '+254', 'flag' => '🇰🇪'],
        ['name' => 'Kuwait', 'code' => '+965', 'flag' => '🇰🇼'],
        ['name' => 'Lebanon', 'code' => '+961', 'flag' => '🇱🇧'],
        ['name' => 'Libya', 'code' => '+218', 'flag' => '🇱🇾'],
        ['name' => 'Malaysia', 'code' => '+60', 'flag' => '🇲🇾'],
        ['name' => 'Mexico', 'code' => '+52', 'flag' => '🇲🇽'],
        ['name' => 'Morocco', 'code' => '+212', 'flag' => '🇲🇦'],
        ['name' => 'Netherlands', 'code' => '+31', 'flag' => '🇳🇱'],
        ['name' => 'New Zealand', 'code' => '+64', 'flag' => '🇳🇿'],
        ['name' => 'Nigeria', 'code' => '+234', 'flag' => '🇳🇬'],
        ['name' => 'Norway', 'code' => '+47', 'flag' => '🇳🇴'],
        ['name' => 'Oman', 'code' => '+968', 'flag' => '🇴🇲'],
        ['name' => 'Pakistan', 'code' => '+92', 'flag' => '🇵🇰'],
        ['name' => 'Palestine', 'code' => '+970', 'flag' => '🇵🇸'],
        ['name' => 'Philippines', 'code' => '+63', 'flag' => '🇵🇭'],
        ['name' => 'Poland', 'code' => '+48', 'flag' => '🇵🇱'],
        ['name' => 'Portugal', 'code' => '+351', 'flag' => '🇵🇹'],
        ['name' => 'Qatar', 'code' => '+974', 'flag' => '🇶🇦'],
        ['name' => 'Romania', 'code' => '+40', 'flag' => '🇷🇴'],
        ['name' => 'Russia', 'code' => '+7', 'flag' => '🇷🇺'],
        ['name' => 'Saudi Arabia', 'code' => '+966', 'flag' => '🇸🇦'],
        ['name' => 'Singapore', 'code' => '+65', 'flag' => '🇸🇬'],
        ['name' => 'South Africa', 'code' => '+27', 'flag' => '🇿🇦'],
        ['name' => 'South Korea', 'code' => '+82', 'flag' => '🇰🇷'],
        ['name' => 'Spain', 'code' => '+34', 'flag' => '🇪🇸'],
        ['name' => 'Sri Lanka', 'code' => '+94', 'flag' => '🇱🇰'],
        ['name' => 'Sudan', 'code' => '+249', 'flag' => '🇸🇩'],
        ['name' => 'Sweden', 'code' => '+46', 'flag' => '🇸🇪'],
        ['name' => 'Switzerland', 'code' => '+41', 'flag' => '🇨🇭'],
        ['name' => 'Syria', 'code' => '+963', 'flag' => '🇸🇾'],
        ['name' => 'Taiwan', 'code' => '+886', 'flag' => '🇹🇼'],
        ['name' => 'Thailand', 'code' => '+66', 'flag' => '🇹🇭'],
        ['name' => 'Tunisia', 'code' => '+216', 'flag' => '🇹🇳'],
        ['name' => 'Turkey', 'code' => '+90', 'flag' => '🇹🇷'],
        ['name' => 'Ukraine', 'code' => '+380', 'flag' => '🇺🇦'],
        ['name' => 'United Arab Emirates', 'code' => '+971', 'flag' => '🇦🇪'],
        ['name' => 'United Kingdom', 'code' => '+44', 'flag' => '🇬🇧'],
        ['name' => 'United States', 'code' => '+1', 'flag' => '🇺🇸'],
        ['name' => 'Vietnam', 'code' => '+84', 'flag' => '🇻🇳'],
        ['name' => 'Yemen', 'code' => '+967', 'flag' => '🇾🇪'],
    ],
    'default_code' => '+966',
];
